# Generated by Django 2.0 on 2018-06-16 09:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans', to='blog.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
